name: Sumbit a theme
description: Submit a theme to be added to the theme library.
title: "[create-theme]: "
labels: ["new-theme"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the theme.
      placeholder: Theme Name
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A brief description of the theme.
      placeholder: Theme Description
    validations:
      required: true
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: The URL of the theme's homepage or repository.
      placeholder: Theme Homepage
    validations:
      required: true
  - type: textarea
    id: styles
    attributes:
      label: Theme Styles
      render: css
      description: The CSS styles for the theme.
      placeholder: |
        body {
          background-color: white;
          color: black;
        }
    validations:
      required: true
  - type: textarea
    id: readme
    attributes:
      render: markdown
      label: Readme
      description: The README file for the theme.
    validations:
      required: true